#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17379
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Avanet.RSS
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	public partial class FavoritosDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
	#region Extensibility Method Definitions
	partial void OnCreated();
	partial void InsertFavorito(Favorito instance);
	partial void UpdateFavorito(Favorito instance);
	partial void DeleteFavorito(Favorito instance);
	#endregion
		
		public FavoritosDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public FavoritosDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Favorito> Favoritos
		{
			get
			{
				return this.GetTable<Favorito>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="")]
	public partial class Favorito : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Identificador;
		
		private string _Titulo;
		
		private string _Resumen;
		
		private string _Enlace;
		
	#region Extensibility Method Definitions
	partial void OnLoaded();
	partial void OnValidate(System.Data.Linq.ChangeAction action);
	partial void OnCreated();
	partial void OnIdentificadorChanging(string value);
	partial void OnIdentificadorChanged();
	partial void OnTituloChanging(string value);
	partial void OnTituloChanged();
	partial void OnResumenChanging(string value);
	partial void OnResumenChanged();
	partial void OnEnlaceChanging(string value);
	partial void OnEnlaceChanged();
	#endregion
		
		public Favorito()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Identificador", CanBeNull=false, IsPrimaryKey=true)]
		public string Identificador
		{
			get
			{
				return this._Identificador;
			}
			set
			{
				if ((this._Identificador != value))
				{
					this.OnIdentificadorChanging(value);
					this.SendPropertyChanging();
					this._Identificador = value;
					this.SendPropertyChanged("Identificador");
					this.OnIdentificadorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Titulo", CanBeNull=false)]
		public string Titulo
		{
			get
			{
				return this._Titulo;
			}
			set
			{
				if ((this._Titulo != value))
				{
					this.OnTituloChanging(value);
					this.SendPropertyChanging();
					this._Titulo = value;
					this.SendPropertyChanged("Titulo");
					this.OnTituloChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Resumen", CanBeNull=false)]
		public string Resumen
		{
			get
			{
				return this._Resumen;
			}
			set
			{
				if ((this._Resumen != value))
				{
					this.OnResumenChanging(value);
					this.SendPropertyChanging();
					this._Resumen = value;
					this.SendPropertyChanged("Resumen");
					this.OnResumenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Enlace", CanBeNull=false)]
		public string Enlace
		{
			get
			{
				return this._Enlace;
			}
			set
			{
				if ((this._Enlace != value))
				{
					this.OnEnlaceChanging(value);
					this.SendPropertyChanging();
					this._Enlace = value;
					this.SendPropertyChanged("Enlace");
					this.OnEnlaceChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
